### ISSUE TITLE
where can I download S2VT?

### ISSUE THREAD

**Issue by shanYanGuan** [vijayvee/video-captioning#1]
hello! I met the problem like this: 
```
 File "/home/gsy/video-captioning/utils.py", line 8, in <module>
    from VideoCap import S2VT
ImportError: No module named VideoCap
```
I think maybe your code doesn't include S2VT .I have found so many code,but it still missed.... Could you give me some guide? thanks!

**Comment by vijayvee** [comment]
Hello @shanYanGuan,

That line can be commented out. I just noticed that it is insignificant.
