### ISSUE TITLE
Can I get the extracted feature files of MSVD video as i am having trouble installing Caffe on my system.

### ISSUE THREAD

**Issue by GauravKrRoy** [vijayvee/video-captioning#19]

**Comment by AsimJalwana** [comment]
Hey Gaurav,
You can find them at https://github.com/vsubhashini/caffe/tree/recurrent/examples/s2vt.  Where you can find the link to extracted features, currently it is https://www.dropbox.com/sh/whatkfg5mr4dr63/AACKCO3LwSsHK4_GOmHn4oyYa?dl=0.

**Comment by abhaygargab** [comment]
If this is still an issue, you can modify Extract_Feats.py following https://github.com/keras-team/keras/issues/4301, and extract the VGG features using keras pretrained VGG16 model. I used zaoyehuo's code given in the above link. 
In this you can get away with installing Caffe

**Comment by vijayvee** [comment]
Closing this issue as there are ways to download the extracted features at https://www.dropbox.com/sh/whatkfg5mr4dr63/AACKCO3LwSsHK4_GOmHn4oyYa?dl=0
