### ISSUE TITLE
Extract_Feats.py

### ISSUE THREAD

**Issue by VisheshTanwar-IITR** [vijayvee/video-captioning#2]
@vijayvee 
Hello Vijay,

I have doubt to know about path defined in "sys.path.insert(0,'/home/vijay/deep-learning/caffe/python')".

Which path is given here? Should I need to give my python path?
Also, where you call this file?

Thanks

**Comment by vijayvee** [comment]
Hello Vishesh,

I extract features using Caffe. This path should point to the caffe installation in your system. You may refer this [guide](http://installing-caffe-the-right-way.wikidot.com/start) to install Caffe.

**Comment by VisheshTanwar-IITR** [comment]
Thanks @vijayvee 

I got that path.
