### ISSUE TITLE
Channel Reversal for VGG

### ISSUE THREAD

**Issue by AsimJalwana** [vijayvee/video-captioning#21]
Hi,  Looking at the feature extraction part, I cannot see if you have reversed the channels to BGR from the RGB frames. Have you trained the VGG network on RGB? Please confirm.

**Comment by vijayvee** [comment]
Hi Asim, good call, I don't think I do the channel reversal in the input pipeline. Corrected this in the feature extraction part.

**Comment by AsimJalwana** [comment]
Thanks Vijay for the reply and correction, Cheers!
