### ISSUE TITLE
IOError Please help

### ISSUE THREAD

**Issue by yanwencai001** [vijayvee/video-captioning#22]
I downloaded your model and extracted features, but it still report errors when I run the test_videocap.py code. Please help.
IOError: Cannot parse file S2VT_Dyn_10_0.0001_300_46000.ckpt.meta: 1:1 : Message type "tensorflow.MetaGraphDef" has no field named "version"..

**Comment by abhaygargab** [comment]
I had the same problem and solved it by downloading all the .ckpt files separately.
When you clone the repository the .ckpt files saved are in Kbs, but after downloading separately those will be in Mbs with the correct format.

**Comment by vijayvee** [comment]
Thanks for the input, please let me know if this doesn't work @yanwencai.
