### ISSUE TITLE
can not find S2VT_Dyn_10_0.0001_300_46000.ckpt.meta ?

### ISSUE THREAD

**Issue by qiangzhang007** [vijayvee/video-captioning#4]
hi ， i got below error.
  IOError: File S2VT_Dyn_10_0.0001_300_46000.ckpt.meta does not exist
 what can i do?

**Comment by vijayvee** [comment]
Hello @qiangzhang007, this is the checkpoint where I saved my trained model. You could train your own model using my repo. I shall also upload the link to download my checkpoints file as soon as I can. Thanks.
