### ISSUE TITLE
The download link redirects to Microsoft store.

### ISSUE THREAD

**Issue by HimaVarsha94** [vijayvee/video-captioning#5]

**Comment by vijayvee** [comment]
Hello Hima, I just checked the link and it seems to be fine. Please select the Download option on the provided link, or use the one below.

[https://download.microsoft.com/download/5/D/5/5D542AEA-7347-4637-9EFF-96998C408FF9/VideoDescriptions.msi](https://download.microsoft.com/download/5/D/5/5D542AEA-7347-4637-9EFF-96998C408FF9/VideoDescriptions.msi)
